### ISSUE TITLE
 ERROR in AbpModule is not an NgModule when using angular-cli

### ISSUE THREAD

**Issue by iyhammad** [aspnetboilerplate/abp-ng2-module#1]
Hi @hikalkan,
I don't know if you are accepting issues on this repository or not. In case you are accepting issues, I'm facing one.
If I do **ng build** using angular-cli I got this issue. I've only imported the **AbpModule** in my main app

> ERROR in AbpModule is not an NgModule

my app is using the below Packages 

- "@angular/cli": "1.0.0-beta.32.3"
- "@angular/compiler-cli": "2.4.7"
- "abp-ng2-module": "^0.2.1"

Thanks,

**Comment by hikalkan** [comment]
Sure, we are accepting, thanks.

We are using;

"@angular/cli": "1.0.0-beta.31"
"@angular/compiler-cli": "2.4.0"
"abp-ng2-module": "^0.2.1"

and have no problem. "AbpModule is not an NgModule" doesn't make sense because it explicitly declares NgModule decorator as you see: https://github.com/aspnetboilerplate/abp-ng2-module/blob/master/src/abp.module.ts#L28
Maybe somehow it's not being compiled. I could not understand.

**Comment by iyhammad** [comment]
Hi @hikalkan,
I think It's a general issue with some shared modules due to Angular recent changes. I found this issue in many libraries and many resolved it already.

Steps to reproduce.

In command Prompt
`
ng  new "app-name" 
`
Once Created Run 
`
ng build
`
It will be built successfully.
Try to add and import AbpModule in app.module.ts and then ng build again. you will see the error
Also If you try to import ABP_HTTP_PROVIDER and add it to the providers array it will make another issue.

**Comment by hikalkan** [comment]
Thank you for more info. We'll try it.

**Comment by iyhammad** [comment]
Proposed solution 
https://github.com/angular/angular-cli/issues/3426#issuecomment-269673735

**Comment by iyhammad** [comment]
I will close this issue as when use the library the same way in the template (have shortcut ti the src folder and use the code in it) it works fine.
